// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0_ZIJqiZym4CYsMrnSJuYJRagqNWfyjs',
    appId: '1:1024350131309:web:5a4b0a932783c7e1541b64',
    messagingSenderId: '1024350131309',
    projectId: 'todoapp-d2070',
    authDomain: 'todoapp-d2070.firebaseapp.com',
    storageBucket: 'todoapp-d2070.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL913QIdsy6TmRK0ezhX-QOgWxHg-IdUs',
    appId: '1:1024350131309:android:5b61148e4c510646541b64',
    messagingSenderId: '1024350131309',
    projectId: 'todoapp-d2070',
    storageBucket: 'todoapp-d2070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXcOhIYADBtN6l10hjQqV32PhHdwhjzDw',
    appId: '1:1024350131309:ios:96146d76783ff10e541b64',
    messagingSenderId: '1024350131309',
    projectId: 'todoapp-d2070',
    storageBucket: 'todoapp-d2070.appspot.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXcOhIYADBtN6l10hjQqV32PhHdwhjzDw',
    appId: '1:1024350131309:ios:96146d76783ff10e541b64',
    messagingSenderId: '1024350131309',
    projectId: 'todoapp-d2070',
    storageBucket: 'todoapp-d2070.appspot.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0_ZIJqiZym4CYsMrnSJuYJRagqNWfyjs',
    appId: '1:1024350131309:web:4384b57c3022093d541b64',
    messagingSenderId: '1024350131309',
    projectId: 'todoapp-d2070',
    authDomain: 'todoapp-d2070.firebaseapp.com',
    storageBucket: 'todoapp-d2070.appspot.com',
  );
}
